version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: admin-backend-api
    environment:
      TZ: Asia/Shanghai
      NODE_ENV: production
      DATABASE_URL: mysql://pk_credit_core_pro_user:qie7rjuzn5nvs35t3znhdk7lamsgh0%40@rm-d9j40fh5e5ny3vr23zo.mysql.ap-southeast-5.rds.aliyuncs.com:3306/pk_credit_admin?ssl=true
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - admin-network
    volumes:
      - ./backend/uploads:/app/uploads

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: admin-backend-web
    environment:
      TZ: Asia/Shanghai
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - admin-network

volumes:
  postgres_data:

networks:
  admin-network:
    driver: bridge
