version: '3.8'

services:
  backend:
    image: ghcr.io/kanlina/admin-backend-system-backend:main
    container_name: admin-backend-api-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=mysql://pk_credit_core_pro_user:qie7rjuzn5nvs35t3znhdk7lamsgh0%40@rm-d9j40fh5e5ny3vr23.mysql.ap-southeast-5.rds.aliyuncs.com:3306/pk_credit_admin
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=7d
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=10485760
    ports:
      - "3001:3001"
    volumes:
      - /var/uploads/admin-backend-prod:/app/uploads
      - /var/log/admin-backend-prod:/app/logs
    networks:
      - admin-backend-system_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  frontend:
    image: ghcr.io/kanlina/admin-backend-system-frontend:main
    container_name: admin-backend-web-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/log/admin-backend-prod:/var/log/nginx
    networks:
      - admin-backend-system_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  admin-backend-system_default:
    driver: bridge
